[phases.setup]
packages = [
    "python3",
    "gcc",
    "python3-dev",
    "libmysqlclient-dev",   # critical for mysqlclient
    "pkg-config",           # needed for pkg-config detection
    "build-essential",
    "libssl-dev",
    "libffi-dev
]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn Elegence_wear_final.wsgi:application --bind 0.0.0.0:$PORT"
