# Generated by Django 5.2.5 on 2025-08-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(blank=True),
        ),
    ]
